### PR TITLE
Update to 17.2.0

### PR DESCRIPTION
**Pull request by aldanor**
@vamega Done, does this look ok?

### CODE REVIEW

**Comment by aldanor** [comment]
Travis and AppVeyor failed but it seems unrelated... (e.g. https://github.com/pelson/Obvious-CI/pull/67)

**Comment by aldanor** [comment]
@jakirkham Apologies, would you happen to know why both Travis and AppVeyor builds seem to be failing at bootstrapping? Is there anything in particular that has to be done here?

**Comment by jakirkham** [comment]
@conda-forge-admin, please rerender.

**Comment by jakirkham** [comment]
@aldanor, the CI configuration files were out of date. Looks like the bot has updated them.

We may want to consider making this package a `noarch: python` package as well. Details in the conda-forge docs (links below). This will speed up the testing and release time. Hence is generally preferred for pure Python packages that are OS independent (without OS specific dependencies) and Python 2/3 compatible (without backport packages). Please take a look and let me know if you have any questions.

ref: https://conda-forge.org/docs/meta.html#building-noarch-packages
ref: https://conda-forge.org/docs/webservice.html#conda-forge-admin-please-add-noarch-python

**Comment by aldanor** [comment]
@jakirkham Thanks! This seems to do it.

I've added `noarch: python` to the build section since this is a pure Python package -- however, I see that AppVeyor and Travis builds are still triggered; isn't it supposed to be just CircleCI for noarch builds?

**Comment by jakirkham** [comment]
@conda-forge-admin, please rerender.

**Comment by jakirkham** [comment]
Yeah it needs to be re-rendered after that change. Should be fixed now.

**Comment by jakirkham** [comment]
As to the discoveries you made with respect to Obvious-CI, we used to use that in conda-forge. However we have since gutted that from the CIs. So this is more a sign of this feedstock being a bit outdated CI configuration-wise. Good rule of thumb is if something seems off, try re-rendering it. Chance are pretty good that just fixes the issue. Anyone can ask the bot to do this or do it manually if they prefer. So it should be a pretty easy thing to try.

**Comment by jakirkham** [comment]
LGTM. @vamega would you able to take a quick look?

**Comment by vamega** [comment]
Thanks @jakirkham  and @aldanor

**Pull request merged**
